### ISSUE TITLE
Throttle speed for more accurate simulation

### ISSUE THREAD

**Issue by BleuLlama** [inexorabletash/jsbasic#20]
It would be nice to have a setting somewhere to throttle the speed to be reasonably close to operation on a real Apple II.  I have some code that uses FOR I=0 TO 1000: NEXT I type busy loops for timing, and it runs way too fast, of course. ;)

I can add it in for myself too, but I do not know the best/correct place to put it.

**Comment by inexorabletash** [comment]
If you look in index.js - https://github.com/inexorabletash/jsbasic/blob/master/index.js#L227 - there's a place where it defines how many commands to run before yielding. It then uses `setTimeout(..., 0)` to yield to the browser for layout/rendering; that will be a 4ms pause on most seconds.

This section could be reworked so that it runs about 1000 steps/second or whatever it takes to match some average real hardware benchmark, and then have an option to run flat out (current code) or try to match real speed. The math will be interesting; it can't yield after every single step since that'd only allow 250 steps/second (due to the clamping of setTimeout to 4ms in most browsers). If each statement was instant, you could run 4 then yield to get 1000/sec, but the statements do take time so this would need to be dynamic.

PRs welcome - have fun!

**Comment by BleuLlama** [comment]
Aha!  I didn't see that.  It's the  Seems like a value of about 50 works for my needs.  I broke it out to a variable at the top.

For future reference, the specific "setTimeout" you mention is at  https://github.com/inexorabletash/jsbasic/blob/master/index.js#L254

I changed the ,0 to ,50, to get reasonably closeish results. ;)  I also broke it out to a variable/setting as well, right next to the one you pointed out at #L227.
