### ISSUE TITLE
Sample adventure crashes; not completable

### ISSUE THREAD

**Issue by dfabulich** [inexorabletash/jsbasic#36]
To repro: https://www.calormen.com/jsbasic/

1. Click the Select a sample… drop down
2. In the Games section, select "Text Adventure (Floyd McWilliams)"
3. Click Run
4. Run these commands:
* e
* u
* n
* take key
* s
* w
* w
* unlock door
* open left door (it doesn't matter which door you open)

A JS alert appears, "Illegal quantity in line 7130"

<img width="1260" alt="Screen Shot 2020-07-26 at 8 35 16 PM" src="https://user-images.githubusercontent.com/96150/88501176-8eb14580-cf7f-11ea-82c6-b876db51064b.png">

**Comment by jonatasdemello** [comment]
Hi,
when you type "OPEN LEFT DOOR"
line 7120 calculates ARG as the second word number stored in INPTK(2) = 31 (LEFT) or 31 (CENTER) or 33 (RIGHT) 
subtracted by ITEMOFF = 33 (line 700)
which translates to: 
ARG = 31 - 33 = -2
this happens because INPTK(2) will always be lower than ITEMOFF (=33)
and it will fail on line 7130 because ILOC(ARG) translates to ILOC(-2)
and arrays can't have negative indexes.

So, in line 7120, instead of:

`7120 ARG = INPTK(2) - ITEMOFF`

if we just swith the order of the parameters (and leave the rest of the line after the : untouched)

`7120 ARG = ITEMOFF - INPTK(2)`

everything works correctly.

**Comment by inexorabletash** [comment]
Yeah, a PR is welcome.

**Comment by jonatasdemello** [comment]
Hi,
I created a PR to fix the "Illegal quantity in line 7130" error.

There are some investigation documents and more information in my other [repository](https://github.com/jonatasdemello/python-games/tree/main/Uncle-Tay-House)

I was planning on converting it to Python or C# sometime in the future, so I could unit test it...
and I was adding another games too, such as Start Trek and "The Horrible Rotten Dancing Dragon".
I'll create another PR when everything is tested and working properly.

Thank you.

**Comment by inexorabletash** [comment]
Fixed by #48 - thanks!

**Comment by jonatasdemello** [comment]
@dfabulich 
Can you test it again?
Thank you!
